### ISSUE TITLE
addressable gem 2.6.0 対応

### ISSUE THREAD

**Issue by tsutsui** [toshia/diva#3]
mikutter 本体のチケットにも書いていますが
diva の addressable gem の要求バージョンについて
2.6.0 も受け入れるように変更しませんか、という提案です
https://dev.mikutter.hachune.net/issues/1330

> https://github.com/toshia/diva/blob/v0.3.2/diva.gemspec#L27
> ```
>  spec.add_dependency "addressable", ">= 2.5", "< 2.6"
> ```
> 
> addressable gem のコミットログを見る限り、
> 2.5.2 → 2.6.0 へ minor バージョンが上げられたのは
> ruby 2.6 サポートと bundle 2.x のサポートという気がします。
> 過去の minor bump を見ても ruby のバージョン絡みのみっぽいので、
> とりあえず <3.0 指定でもいいんじゃないかという気がします。
> 
> 手元で試したところでは mikutter 3.8.7 + diva 0.3.2 で
> addressable 2.6.0 でもTLを眺めるのに支障がないくらいには
> 動いているようです。
> (addressable gem がどこで参照されるのかを把握していない)

**Comment by toshia** [comment]
ありがとうございます。v1.0.0で対応しました。

> とりあえず <3.0 指定でも

確かに言われてみればそれでも良かったかもしれない

**Comment by dai-vdr** [comment]
(ほぼ同内容なのでオープンされているこのイシューに記載します)

addressable 2.7.0 がリリースされました。
divaのテストケースはそのままパスし、mikutterも動作に支障なさそうです。
ご対応お願いいたします。

**Comment by tsutsui** [comment]
close処理するのをすっかり忘れていました……。

addressable 2.7.0 の CHANGELOG.md では
https://github.com/sporkmonger/addressable/blob/addressable-2.7.0/CHANGELOG.md
```
# Addressable 2.7.0
- added `:compacted` flag to `normalized_query`
- `heuristic_parse` handles `mailto:` more intuitively
- dropped explicit support for JRuby 9.0.5.0
- compatibility w/ public_suffix 4.x
- performance improvements
```
ということなので特に問題はなさそうですね。


pkgsrc では addressable が依存する public_suffix についても
4.0.1 に上げてしまおうかと思います。
https://rubygems.org/gems/public_suffix/versions/4.0.1

**Comment by toshia** [comment]
私の方でも確認して良さそうだと思ったので、addressable 2.7を許容するdiva 1.0.1をリリースしました。

**Comment by dai-vdr** [comment]
対応ありがとうございます。Debianパッケージ更新しました。

**Comment by tsutsui** [comment]
pkgsrc 更新して public_suffix 4.0.1 + addressable 2.7.0 + diva 1.0.1 で mikutter develop 動いているのでクローズします
