### ISSUE TITLE
addressable gem 2.8.0 対応

### ISSUE THREAD

**Issue by tsutsui** [toshia/diva#4]
#3 と同じ内容ですが
2021/7 に addressable gem 2.8.0 が出ています。
https://github.com/sporkmonger/addressable/blob/addressable-2.8.0/CHANGELOG.md

diva の `diva.gemspec` では `">= 2.5.2", "< 2.8"` のままなので引っかかります。
https://github.com/toshia/diva/blob/da69398f7f8766e0b05fe5e334463ee006dcb5b5/diva.gemspec#L27

変更点はざっくり "dropping support for Ruby 2.0 and 2.1" と "adding Ruby 3.0" で、
細かい非互換っぽく見える変更はありますが、 diva で参照しているかどうか?

とりあえず 2.8 まで許容するか `"<3.0"` とするか、どちらかお願いしたいです。

**Comment by toshia** [comment]
`"<3.0"` にして、 diva 1.0.3としてリリースしました。

**Comment by toshia** [comment]
@tsutsui `"<3.0"` にして、 diva 1.0.3としてリリースしました。
